### ISSUE TITLE
bad lua script for redis cluster, all the keys that the script uses should be passed using the KEYS array, and KEYS should not be in expression

### ISSUE THREAD

**Issue by orangemi** [thunks/thunk-ratelimiter#1]
https://github.com/thunks/thunk-ratelimiter/blob/master/ratelimite.lua#L12
https://github.com/thunks/thunk-ratelimiter/blob/master/ratelimite.lua#L13

These 2 lines use different hashed key (L12 with `{KEYS[1]}`, but L13 use `KEYS[1]`) maybe stored in different shard. This will trigger redis-cluster error:
```
bad lua script for redis cluster, all the keys that the script uses should be passed using the KEYS array, and KEYS should not be in expression
```

L13 should use the same hash strategy for `KEYS[1]`

**Comment by zensh** [comment]
It is a problem of aliyun redis cluster: https://help.aliyun.com/document_detail/26356.html

**Comment by LeonJob1492** [comment]
https://github.com/redisson/redisson/issues/1538
